// const host = "http://localhost:3000";
const host = "http://localhost:5001";
export const setAvatarAPI = `${host}/api/auth/setAvatar`;
export const registerAPI = `${host}/api/auth/register`;
export const loginAPI = `${host}/api/auth/login`;
export const addTransaction = `${host}/api/transactions/addTransaction`;
export const getTransactions = `${host}/api/transactions/getTransaction`;
export const editTransactions = `${host}/api/transactions/updateTransaction`;
export const deleteTransactions = `${host}/api/transactions/deleteTransaction`;
